// react/src/components/product-list/ProductList.tsx
import styles from './ProductList.module.css';
import {confirmPopup, ConfirmPopup} from "primereact/confirmpopup";
import {useCallback, useEffect} from "react";
import {Card} from "primereact/card";
import {observer} from "mobx-react-lite";
import {Button} from "primereact/button";
import {Link} from "react-router-dom";
import {ProductAlerts} from "./product-alerts/ProductAlerts";
import ProductListStore from "./ProductListStore";

export const ProductList = observer(() => {
    const store = ProductListStore;

    const sharePopupFunc = useCallback((event: any) => {
        confirmPopup({
            target: event.currentTarget!,
            message: 'The product has been shared successfully',
            rejectClassName: 'productListRejectClass'
        })
    }, [])
    const notifyPopupFunc = useCallback((event: any) => {
        confirmPopup({
            target: event.currentTarget!,
            message: 'You will be notified when the product goes on sale',
            rejectClassName: 'productListRejectClass'
        })
    }, [])

    useEffect(() => {
        store.fetchProducts()
    }, [])

    return (
        <div className="product-list-content">
            <h2>Products</h2>

            <ConfirmPopup/>

            {store.products.map(product => {
                return (
                    <Card
                        className={styles.card}
                        key={product.id}
                        header={
                            <h3 className={styles.header}>
                                <Link to={'/products/' + product.id}>{product.name}</Link>
                            </h3>}
                        footer={
                            <div className={styles.footer}>
                                <Button type="button" onClick={sharePopupFunc} className={styles.shareButton}>Share</Button>
                                <ProductAlerts notify={notifyPopupFunc} product={product}/>
                            </div>}
                    >
                        {product.description && <p>Description: {product.description}</p>}
                    </Card>
                )
            })}
        </div>
    )
})

// angular/src/app/product-list/product-list.component.ts
import {Component, OnInit} from '@angular/core';
import {Product} from "../Product";
import {ProductsService} from "./products.service";
import {ConfirmationService} from "primeng/api";

@Component({
    selector: 'app-product-list',
    templateUrl: './product-list.component.html',
    styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {

    products: Product[] = [];

    constructor(private productService: ProductsService, private confirmationService: ConfirmationService) {
    }

    ngOnInit(): void {
        this.productService.products$.subscribe(products => this.products = products);
    }

    share(event: Event) {
        this.confirmationService.confirm({
            target: event.target as EventTarget,
            message: 'The product has been shared successfully',
            rejectVisible: false,
        })
    }

    onNotify(event: Event) {
        this.confirmationService.confirm({
            target: event.target as EventTarget,
            message: 'You will be notified when the product goes on sale',
            rejectVisible: false,
        })
    }
}

<h2>Products</h2>

<p-confirmPopup></p-confirmPopup>

<div *ngFor="let product of products">
    <h3>
        <a [routerLink]="['/products', product.id]"
           [title]="product.name + ' details'">
            {{ product.name }}
        </a>
    </h3>

    <p *ngIf="product.description">
        Description: {{ product.description }}
    </p>

    <p-button (click)="share($event)" type="button">
        Share
    </p-button>

    <app-product-alerts (notify)="onNotify($event)" [product]="product"></app-product-alerts>
</div>
